#pragma once

#define USBD_MAX_NUM_INTERFACES     1U
#define USBD_MAX_NUM_CONFIGURATION     1U
#define USBD_MAX_STR_DESC_SIZ     512U
#define USBD_SUPPORT_USER_STRING_DESC     1U
#define USBD_DEBUG_LEVEL     0U
#define USBD_LPM_ENABLED     1U
#define USBD_SELF_POWERED     0U

#define DEVICE_FS 		0
#define DEVICE_HS 		1
